### ISSUE TITLE
Crash in Additional5GSecurityInformation

### ISSUE THREAD

**Issue by lakshmankumar12** [my5G/my5G-RANTester#56]
On running `app ue` , get this crash:

```
ubuntu@ubuntu-server:~/my5G-RANTester/cmd$ ./app ue
INFO[0000] my5G-RANTester version 1.0.1
INFO[0000] ---------------------------------------
INFO[0000] [TESTER] Starting test function: Testing an ue attached with configuration
INFO[0000] [TESTER][UE] Number of UEs: 1
INFO[0000] [TESTER][GNB] Control interface IP/Port: 192.168.60.1/9487
INFO[0000] [TESTER][GNB] Data interface IP/Port: 192.168.60.1/2152
INFO[0000] [TESTER][AMF] AMF IP/Port: 192.168.60.142/38412
INFO[0000] ---------------------------------------
INFO[0000] [GNB] SCTP/NGAP service is running
INFO[0000] [GNB] UNIX/NAS service is running
INFO[0000] [GNB][SCTP] Receive message in 0 stream
INFO[0000] [GNB][NGAP] Receive Ng Setup Response
INFO[0000] [GNB][AMF] AMF Name: MAGMAAMF1
INFO[0000] [GNB][AMF] State of AMF: Active
INFO[0000] [GNB][AMF] Capacity of AMF: 11
INFO[0000] [GNB][AMF] PLMNs Identities Supported by AMF -- mcc: 001 mnc:01
INFO[0000] [GNB][AMF] List of AMF slices Supported by AMF -- sst:01 sd:was not informed
INFO[0001] [UE] UNIX/NAS service is running
INFO[0001] [GNB][SCTP] Receive message in 1 stream
INFO[0001] [GNB][NGAP] Receive Downlink NAS Transport
INFO[0001] [UE][NAS] Message without security header
INFO[0001] [UE][NAS] Receive Authentication Request
INFO[0001] [UE][NAS][MAC] Authenticity of the authentication request message: OK
INFO[0001] [UE][NAS][SQN] SQN of the authentication request message: VALID
INFO[0001] [UE][NAS] Send authentication response
INFO[0001] [GNB][SCTP] Receive message in 1 stream
INFO[0001] [GNB][NGAP] Receive Downlink NAS Transport
INFO[0001] [UE][NAS] Message with security header
INFO[0001] [UE][NAS] Message with integrity and with NEW 5G NAS SECURITY CONTEXT
INFO[0001] [UE][NAS] successful NAS MAC verification
INFO[0001] [UE][NAS] Receive Security Mode Command
INFO[0001] [UE][NAS] Type of ciphering algorithm is 5G-EA0
INFO[0001] [UE][NAS] Type of integrity protection algorithm is 128-5G-IA2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x69b7cc]

goroutine 38 [running]:
my5G-RANTester/lib/nas/nasType.(*Additional5GSecurityInformation).GetRINMR(...)
        /home/ubuntu/my5G-RANTester/lib/nas/nasType/NAS_Additional5GSecurityInformation.go:45
my5G-RANTester/internal/control_test_engine/ue/nas/handler.HandlerSecurityModeCommand(0xc0000b8000?, 0xc000217480)
        /home/ubuntu/my5G-RANTester/internal/control_test_engine/ue/nas/handler/handler.go:83 +0x28c
my5G-RANTester/internal/control_test_engine/ue/nas.DispatchNas(0xc00020a000, {0xc0002143f0, 0x12, 0x12})
        /home/ubuntu/my5G-RANTester/internal/control_test_engine/ue/nas/dispatcher.go:142 +0xc9a
my5G-RANTester/internal/control_test_engine/ue/state.DispatchState(0xc00010e680?, {0xc0002143f0?, 0x2a?, 0x2a?})
        /home/ubuntu/my5G-RANTester/internal/control_test_engine/ue/state/dispatch.go:15 +0x47
created by my5G-RANTester/internal/control_test_engine/ue/nas/service.UeListen
        /home/ubuntu/my5G-RANTester/internal/control_test_engine/ue/nas/service/service.go:59 +0x5b
ubuntu@ubuntu-server:~/my5G-RANTester/cmd$
```

Attaching the pcap of the packets exchanged with core, and config used.
[crash-on-registration.zip](https://github.com/my5G/my5G-RANTester/files/13897590/crash-on-registration.zip)

**Comment by linouxis9** [comment]
This should be fixed in https://github.com/HewlettPackard/PacketRusher ;-) @lakshmankumar12
